# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LaTeX-Table
version:      v0.0.1
version_from: lib/LaTeX/Table.pm
installdirs:  site
requires:
    Class::Std:                    0
    Regexp::Common:                0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
