---
name: LaTeX-Table
version: v0.99_1
author:
  - 'Markus Riester <mriester@gmx.de>'
abstract: Perl extension for the automatic generation of LaTeX tables.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Spec: 0
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Carp: 0
  Cwd: 0
  English: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Policy::FollowPBP: 0
  Scalar::Util: 0
  Template: 0
  perl: v5.8.0
  version: 0
recommends:
  Getopt::Long: 0
  LaTeX::Driver: 0
  LaTeX::Encode: 0
  Number::Format: 0
  Text::CSV: 0
  autodie: 0
configure_requires:
  Module::Build: 0.34
provides:
  LaTeX::Table:
    file: lib/LaTeX/Table.pm
    version: v0.99_1
  LaTeX::Table::Themes::Beamer:
    file: lib/LaTeX/Table/Themes/Beamer.pm
    version: 1738
  LaTeX::Table::Themes::Booktabs:
    file: lib/LaTeX/Table/Themes/Booktabs.pm
    version: 1741
  LaTeX::Table::Themes::Classic:
    file: lib/LaTeX/Table/Themes/Classic.pm
    version: 1780
  LaTeX::Table::Themes::Modern:
    file: lib/LaTeX/Table/Themes/Modern.pm
    version: 1741
  LaTeX::Table::Themes::ThemeI:
    file: lib/LaTeX/Table/Themes/ThemeI.pm
    version: 1741
  LaTeX::Table::Types::Ctable:
    file: lib/LaTeX/Table/Types/Ctable.pm
    version: 1764
  LaTeX::Table::Types::Longtable:
    file: lib/LaTeX/Table/Types/Longtable.pm
    version: 1779
  LaTeX::Table::Types::Std:
    file: lib/LaTeX/Table/Types/Std.pm
    version: 1764
  LaTeX::Table::Types::TypeI:
    file: lib/LaTeX/Table/Types/TypeI.pm
    version: 1823
  LaTeX::Table::Types::Xtab:
    file: lib/LaTeX/Table/Types/Xtab.pm
    version: 1778
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
