---
name: LaTeX-Table
version: 0.9.7
author:
  - 'Markus Riester <mriester@gmx.de>'
abstract: Perl extension for the automatic generation of LaTeX tables.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  English: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Policy::FollowPBP: 0
  Readonly: 0
  Scalar::Util: 0
  Text::Wrap: 0
  perl: 5.8.0
  version: 0
build_requires:
  File::Spec: 0
  Test::More: 0
  Test::NoWarnings: 0
recommends:
  Getopt::Long: 0
  LaTeX::Driver: 0
  LaTeX::Encode: 0
  Number::Format: 0
  Text::CSV_XS: 0
provides:
  LaTeX::Table:
    file: lib/LaTeX/Table.pm
    version: 0.9.7
  LaTeX::Table::Themes::Beamer:
    file: lib/LaTeX/Table/Themes/Beamer.pm
    version: 1154
  LaTeX::Table::Themes::Booktabs:
    file: lib/LaTeX/Table/Themes/Booktabs.pm
    version: 1154
  LaTeX::Table::Themes::Classic:
    file: lib/LaTeX/Table/Themes/Classic.pm
    version: 1151
  LaTeX::Table::Themes::Modern:
    file: lib/LaTeX/Table/Themes/Modern.pm
    version: 1161
  LaTeX::Table::Themes::ThemeI:
    file: lib/LaTeX/Table/Themes/ThemeI.pm
    version: 1159
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
